name: resq_me
description: "The app that could save your life – Resq Me."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'
dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_phone_direct_caller: ^2.1.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  equatable: ^2.0.5
  user_repository:
    path: packages/user_repository
  maps_launcher: ^2.2.1
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true